phrase:
  project_id: 9ffb33ea18197bb3784239973771c771

  push:
    sources:
      - file: ./public/locales/<locale_name>.json
        params:
          file_format: simple_json
          locale_id: nl

    

  pull:
    targets:
      - file: ./public/locales/<locale_name>.json
        params:
          file_format: simple_json
