phrase:
  project_id: 3ecc830bee3303096199278394350c28

  push:
    sources:
      - file: ./public/locales/<locale_name>.json
        params:
          file_format: simple_json
          locale_id: nl

    

  pull:
    targets:
      - file: ./public/locales/<locale_name>.json
        params:
          file_format: simple_json
