phrase:
  project_id: a9998290a6e33ae59c5299e00f530f0d

  push:
    sources:
      - file: .public/locales/<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en

  pull:
    targets:
      - file: .public/locales/<locale_name>.json
        params:
          file_format: simple_json
