phrase:
  project_id: c4534af4784316e3dc93e986fc474a2f

  push:
    sources:
      - file: ./public/locales/<locale_name>.json
        params:
          file_format: simple_json
          locale_id: en

    

  pull:
    targets:
      - file: ./public/locales/<locale_name>.json
        params:
          file_format: simple_json
