phrase:
  project_id: 1f9d495ef8590714aaebff598c09476f

  push:
    sources:
      - file: ./public/locales/en.json
        params:
          file_format: simple_json
          locale_id: en

  pull:
    targets:
      - file: ./public/locales/en.json
        params:
          file_format: simple_json
